name: Save to today's folder with proper naming

on:
  schedule:
    - cron: '46 9 * * *'  # Run at 9:36 AM every day (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: buithehai1994/bbc-data-crawler

      - name: Setup Python
        uses: buithehai1994/bbc-data-crawler
        with:
          python-version: '3.9'
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute Python script
        run: python function.py

      - name: Move processed file with proper naming
        run: mv filtered_articles.csv processed_files/bbc_articles_$(date +\%Y-\%m-\%d).csv
        
      - name: Commit changes to repository
        uses: buithehai1994/bbc-data-crawler
        with:
          commit_message: "Save processed articles for `date +%Y-%m-%d`"
