name: Python Workflow

on:
  schedule:
    - cron: "16 10 * * *" # Runs every day at 10:06 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  # This workflow contains a single job called "python_workflow"
  python_workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Find and install requirements
      run: |
        for req_file in $(find . -name 'requirements.txt' -print -quit); do
          pip install -r $req_file
          break  # Exit after first successful `requirements.txt` installation
        done

    - name: Execute Python script
      run: python function.py

    - name: Move processed file with proper naming
      run: mv filtered_articles.csv processed_files/bbc_articles_$(date +\%Y-\%m-\%d).csv

    - name: Commit changes to repository
      uses: actions/checkout@v2  # Ensure code is checked out first
    - uses: ./.github/actions/bbc-data-crawler  # Path to your custom GitHub Action
      with:
        commit_message: "Save processed articles for $(date +%Y-%m-%d)"
