name: Python Workflow

on:
  schedule:
    - cron: "16 10 * * *" # Runs every day at 10:06 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  python_workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Install Python packages from all requirements.txt files
      run: |
        python -m pip install --upgrade pip
        REQ_FILES=$(find . -name 'requirements.txt')
        if [ -z "$REQ_FILES" ]; then
          echo "No requirements.txt files found."
          exit 1
        fi
        for REQ_FILE in $REQ_FILES; do
          echo "Installing packages from $REQ_FILE"
          pip install --no-cache-dir -r "$REQ_FILE" || {
            echo "Error installing packages from $REQ_FILE"
            tail -n 20 "$REQ_FILE"
            pip list
            exit 2
          }
        done
        
    - name: Execute Python scripts
      run: |
        echo "Starting Python scripts execution"
        for script in $(find . -name '*.py'); do
          python "$script" &
        done
        wait
        echo "All Python scripts executed"

    - name: Wait for filtered_articles.csv to be generated
      id: check_csv
      run: |
        for i in {1..10}; do
          if [ -f "filtered_articles.csv" ]; then
            echo "filtered_articles.csv is ready"
            break
          else
            echo "Waiting for filtered_articles.csv to be generated... ($i)"
            sleep 60
          fi
        done
        if [ ! -f "filtered_articles.csv" ]; then
          echo "Error: filtered_articles.csv was not generated after 10 attempts"
          exit 1
        fi

    - name: Move processed file with proper naming
      run: |
        if [ -f "filtered_articles.csv" ]; then
          mv filtered_articles.csv processed_files/bbc_articles_$(date +\%Y-\%m-\%d).csv
          echo "Moved filtered_articles.csv to processed_files directory"
        else
          echo "No filtered_articles.csv found, skipping move"
        fi

    - name: Commit and push changes to repository
      run: |
        if [ -f "processed_files/bbc_articles_$(date +\%Y-%m-%d).csv" ]; then
          git add processed_files/
          git commit -m "Save processed articles for $(date +%Y-%m-%d)"
          git push
          echo "Changes committed and pushed"
        else
          echo "Processed CSV not found, skipping git commit and push"
        fi
