name: Python Workflow

on:
  schedule:
    - cron: "23 40 * * *" # Runs every day at 23:40 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  python_workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Python packages from all requirements.txt files
      run: |
        python -m pip install --upgrade pip
        for script in $(find . -name '*.txt'); do
          pip install -r "$script" &
        done
        wait
        echo "All requirements installed"
        
    - name: Execute Python scripts
      run: |
        echo "Starting Python scripts execution"
        for script in $(find . -name 'main.py'); do
          python "$script" &
        done
        wait
        echo "All Python scripts executed"
      
    - name: Commit and push changes to repository
      run: |
        FILE_PATH="processed_files/bbc_articles_$(date '+%Y-%m-%d').json"
        
        if [ -f "$FILE_PATH" ]; then
          # Configure Git with your email and username
          git config --local user.email "haibt0206@gmail.com"
          git config --local user.name "thehaibui"

          # Pull the latest changes from the remote
          git pull origin main
          
          # Stage all changes in the processed_files directory
          git add processed_files/*
          
          # Commit changes with a message including today's date
          git commit -m "Save processed articles for $(date '+%Y-%m-%d')"
          
          # Push changes to the remote repository
          git push
        else
          echo "No processed file found for today, skipping commit"
        fi
        
    - name: Push changes to GitHub
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_PAT_TOKEN }}
        branch: ${{ github.ref_name }}
        directory: processed_files
        force: true
