name: Python Workflow

on:
  schedule:
    - cron: "16 10 * * *" # Runs every day at 10:06 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  # This workflow contains a single job called "python_workflow"
  python_workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r $(find . -name 'requirements.txt' -print -quit)

    - name: Execute Python scripts
      run: |
        for script in $(find . -name '*.py'); do
          python "$script"
        done

    - name: Move processed file with proper naming
      run: |
        if [ -f "filtered_articles.csv" ]; then
          mv filtered_articles.csv processed_files/bbc_articles_$(date +\%Y-\%m-\%d).csv
        else
          echo "No filtered_articles.csv found"
        fi

    - name: Commit and push changes to repository
      run: |
        if [ -f "processed_files/bbc_articles_$(date +\%Y-\%m-\%d).csv" ]; then
          git add processed_files/
          git commit -m "Save processed articles for $(date +%Y-%m-%d)"
          git push
        fi
